import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/navbar";
import Newsletter from "@/components/sections/newsletter";
import Footer from "@/components/sections/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-[#080C15] min-h-[100dvh]  overflow-x-hidden ${inter.className}`}
      >
        <Navbar />
        <main className=" text-white flex flex-col items-center bg-[#080C15] min-h-[100dvh] overflow-x-hidden">
          {children}
          <Newsletter />
          <Footer />
        </main>
      </body>
    </html>
  );
}
